### ISSUE TITLE
add license

### ISSUE THREAD

**Issue by moggle-mog** [jart/gosip#1]
It's a wonderful repo, but I'm so sorry that I can't find license in your repo anywhere, can you add a license please?

**Comment by jart** [comment]
I'm discussing how we want to move forward with that with folks offline. Until then I say just have fun using gosip. We'll keep this thread updated as soon as possible. It's more than likely it'll be fine to do something like Apache 2.0 or MIT or some kind of notice license. Can't make promises yet.

**Comment by jart** [comment]
How does Apache 2.0 sound? Does that meet your requirements?

**Comment by moggle-mog** [comment]
So cool, `Apache 2.0` is enough for me, thank you very much!

**Comment by jart** [comment]
Done. Have fun!

If you use this code for something cool, and feel comfortable sharing details, feel free to let us know in this thread or alternatively reach out to me at jtunney@gmail.com in case there's anything more I can do to help you be successful.

**Comment by jart** [comment]
Done. Have fun!

If you use this code for something cool, and feel comfortable sharing details, feel free to let us know in this thread or alternatively reach out to me at jtunney@gmail.com in case there's anything more I can do to help you be more successful.

**Comment by moggle-mog** [comment]
Got it!
