### ISSUE TITLE
Move dialog into own package

### ISSUE THREAD

**Issue by negbie** [jart/gosip#10]
@jart do you think it makes sense to move out dialog handling into own package?

**Comment by negbie** [comment]
https://github.com/jart/gosip/commit/80e84b29001632380340c0e05d3c9ad3b607dc88

**Comment by negbie** [comment]
Still not sure if it makes sense to create a separate transport package. What do you think?

**Comment by jart** [comment]
Sure we can do that! Now's the best time to improve the API.

**Comment by negbie** [comment]
Done here https://github.com/jart/gosip/commit/332151eb48cc69bafc0110dc54454c321b677959

**Comment by jart** [comment]
Reviewed the code and it looks good to me. Thank you! Feel free to delete branches like `dialog` if you don't need them anymore.

**Comment by negbie** [comment]
Done :)
