### ISSUE TITLE
Extension Header parse failed

### ISSUE THREAD

**Issue by shihzh** [jart/gosip#15]
The following usecase test failed. It same that Extension Header name cannot be substring of Stander Header name.
For example,  Extension Header "Call", "Proxy", "User"  parse failed.
var msgTests = []msgTest{
	{
		name: "Extension Headers",
		s: "SIP/2.0 200 OK\r\n" +
			"Call: omfg\r\n" +
			"\r\n",
		msg: sip.Msg{
			VersionMajor: 2,
			Status:       200,
			Phrase:       "OK",
			XHeader:      &sip.XHeader{Name: "Call", Value: []byte("omfg")},
		},
	}

**Comment by negbie** [comment]
In SIP extension header normally come with the X- prefix. So you should change your test case into this:

```go
var msgTests = []msgTest{
{
name: "Extension Headers",
s: "SIP/2.0 200 OK\r\n" +
"X-Call: omfg\r\n" +
"\r\n",
msg: sip.Msg{
VersionMajor: 2,
Status: 200,
Phrase: "OK",
XHeader: &sip.XHeader{Name: "X-Call", Value: []byte("omfg")},
},
}
```
